//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_fade_H
#define METASPRITE_bg_fade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_fade_TILE_ORIGIN 0
#define bg_fade_TILE_W 8
#define bg_fade_TILE_H 8
#define bg_fade_WIDTH 16
#define bg_fade_HEIGHT 16
#define bg_fade_TILE_COUNT 4
#define bg_fade_PALETTE_COUNT 1
#define bg_fade_COLORS_PER_PALETTE 2
#define bg_fade_TOTAL_COLORS 2
#define bg_fade_PIVOT_X 8
#define bg_fade_PIVOT_Y 8
#define bg_fade_PIVOT_W 16
#define bg_fade_PIVOT_H 16
extern const metasprite_t* const bg_fade_metasprites[1];

BANKREF_EXTERN(bg_fade)

extern const palette_color_t bg_fade_palettes[2];
extern const uint8_t bg_fade_tiles[32];

#endif
