//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(bg_fade)

const palette_color_t bg_fade_palettes[2] = {
	RGB8(  0,  0,  0), RGB8(  0,  0,  0)
};

const uint8_t bg_fade_tiles[32] = {
	0x41,0x82,0x04,0x08,0x10,0x20,0x41,0x82,
	
0xe3,0xc7,0x8e,0x1c,0x38,0x71,0xe3,0xc7,
	
0xf7,0xef,0xdf,0xbe,0x7d,0xfb,0xf7,0xef,
	
0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff
	
};

const metasprite_t bg_fade_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 1, S_PAL(0)),
	METASPR_ITEM(8, -8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 3, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const bg_fade_metasprites[1] = {
	bg_fade_metasprite0
};
