//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_store_owner_H
#define METASPRITE_bg_store_owner_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_store_owner_TILE_ORIGIN 0
#define bg_store_owner_TILE_W 8
#define bg_store_owner_TILE_H 8
#define bg_store_owner_WIDTH 64
#define bg_store_owner_HEIGHT 64
#define bg_store_owner_TILE_COUNT 64
#define bg_store_owner_PALETTE_COUNT 4
#define bg_store_owner_COLORS_PER_PALETTE 4
#define bg_store_owner_TOTAL_COLORS 16
#define bg_store_owner_PIVOT_X 32
#define bg_store_owner_PIVOT_Y 32
#define bg_store_owner_PIVOT_W 64
#define bg_store_owner_PIVOT_H 64
extern const metasprite_t* const bg_store_owner_metasprites[1];

BANKREF_EXTERN(bg_store_owner)

extern const palette_color_t bg_store_owner_palettes[16];
extern const uint8_t bg_store_owner_tiles[1024];

#endif
