//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sframe7_H
#define METASPRITE_sframe7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sframe7_TILE_ORIGIN 0
#define sframe7_TILE_W 8
#define sframe7_TILE_H 8
#define sframe7_WIDTH 24
#define sframe7_HEIGHT 24
#define sframe7_TILE_COUNT 9
#define sframe7_PALETTE_COUNT 1
#define sframe7_COLORS_PER_PALETTE 2
#define sframe7_TOTAL_COLORS 2
#define sframe7_PIVOT_X 12
#define sframe7_PIVOT_Y 12
#define sframe7_PIVOT_W 24
#define sframe7_PIVOT_H 24
extern const metasprite_t* const sframe7_metasprites[1];

BANKREF_EXTERN(sframe7)

extern const palette_color_t sframe7_palettes[2];
extern const uint8_t sframe7_tiles[72];

#endif
