//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sp_store_owner_H
#define METASPRITE_sp_store_owner_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sp_store_owner_TILE_ORIGIN 0
#define sp_store_owner_TILE_W 8
#define sp_store_owner_TILE_H 8
#define sp_store_owner_WIDTH 96
#define sp_store_owner_HEIGHT 32
#define sp_store_owner_TILE_COUNT 48
#define sp_store_owner_PALETTE_COUNT 2
#define sp_store_owner_COLORS_PER_PALETTE 4
#define sp_store_owner_TOTAL_COLORS 8
#define sp_store_owner_PIVOT_X 48
#define sp_store_owner_PIVOT_Y 16
#define sp_store_owner_PIVOT_W 96
#define sp_store_owner_PIVOT_H 32
extern const metasprite_t* const sp_store_owner_metasprites[1];

BANKREF_EXTERN(sp_store_owner)

extern const palette_color_t sp_store_owner_palettes[8];
extern const uint8_t sp_store_owner_tiles[768];

#endif
